### ISSUE TITLE
DevTools bugs

### ISSUE THREAD

**Issue by delphiresources** [hgourvest/dcef3#1]
f you open the DevTools --> Settings --> WorkSpace and click Add Folder, nothing happens, at least on the guiclient demo on which I based some development of mine.

At the same time, if you try to use TimeLine or Profiles, and you want to save on file (.json), the Save window won't open. The Load window, on the contrary, seems to work fine

**Comment by hgourvest** [comment]
it is not related to this project, please report it here:
https://bitbucket.org/chromiumembedded/cef/issues
