### ISSUE TITLE
Crash when using Free (solution)

### ISSUE THREAD

**Issue by felipedaragon** [hgourvest/dcef3#10]
Hi Henri, using branch 2454 and I noticed that the line `FBrowser.Host.CloseBrowser(False)` in TCustomChromium.Destroy is causing the app to close when Free is called. To reproduce it, just try:

```
procedure TForm1.Button1Click(Sender: TObject);
begin
  crm:=TChromium.Create(self);
  crm.Parent:=self;
  crm.Align:=alclient;
  crm.Load('www.google.com');
end;

procedure TForm1.Button2Click(Sender: TObject);
begin
  crm.Free;
end;
```

**Comment by felipedaragon** [comment]
Also: comparing with WACEF, they commented this line out in their 2357 branch

**Comment by hgourvest** [comment]
thanks
