### ISSUE TITLE
Problem when using ReCreateBrowser

### ISSUE THREAD

**Issue by felipedaragon** [hgourvest/dcef3#11]
Henri - Similar to my last report, using branch 2454, the line `SendMessage(FBrowser.Host.WindowHandle, WM_CLOSE, 0, 0)` in ReCreateBrowser is causing the app to close. All fine after commenting it out

**Comment by hgourvest** [comment]
thanks

**Comment by AlexanderPD** [comment]
i'm using branch 2454 and now ReCreateBrowser is not working at all
