### ISSUE TITLE
Issue with 64-bit and OnLoadError event in 2454 branch

### ISSUE THREAD

**Issue by felipedaragon** [hgourvest/dcef3#12]
Hi Henri
Trying to get 2454 to work with Win64, but it is crashing when Load is called. Example code:

```
procedure TForm1.Button1Click(Sender: TObject);
begin
  crm:=TChromium.Create(self);
  crm.Parent:=self;
  crm.Align:=alclient;
  crm.Load('www.google.com');
end;

procedure TForm1.Button2Click(Sender: TObject);
begin
  crm.Free;
end;
```

**Comment by felipedaragon** [comment]
Tested on WinXP 64 and Win10 64. Not working in both

**Comment by delphiresources** [comment]
Have the same problem with 64bit

tested with XE7 on both Windows 8.1 and Window 10

**Comment by permacole** [comment]
Officially CEF3 64 bit is still experimental!
https://cefbuilds.com/

**Comment by hgourvest** [comment]
officially CEF3 64bits is still unstable!
https://cefbuilds.com/

**Comment by felipedaragon** [comment]
But in a curious manner the 64-bit is working with the WACEF branch 2357

**Comment by felipedaragon** [comment]
Haven't tried DCEF3 branch 2378 yet

**Comment by felipedaragon** [comment]
Uh-oh, no way to tell if it works with 2378 https://groups.google.com/forum/#!topic/delphichromiumembedded/IRKXVbmkUew :)

**Comment by RJ35** [comment]
Adding

```
CefSingleProcess := False;
if not CefLoadLibDefault then Exit;
...
Application.Initialize;
```

to your .dpr file should work. (I know it's not necessary when using the 32-bit version, but the 64-bit version seems to require it...)

**Comment by felipedaragon** [comment]
RJ35 - Hello! I'm already using these same lines but it is not working with CEF branch 2454 (for 64-bit)

**Comment by RJ35** [comment]
I use the binary files from cef_binary_3.2454.1344.g2782fb8_windows64 available from
https://cefbuilds.com/.

Use the files in
/Release
/Resources

It's working at my end using Delphi XE6.

**Comment by felipedaragon** [comment]
Hi RJ35 - Thanks, same binaries I'm using for 64-bit, but I get crash when calling the Load method after creating the Chromium object during runtime. I will re-do my tests later today

**Comment by felipedaragon** [comment]
Hi RJ35, try setting the onLoadError event and after this load an invalid URL using the 64-bit release. After I commented out the OnLoadError event, it's working! But if I add it again... :)

**Comment by RJ35** [comment]
I can't confirm it. Sorry!

My test sample is very simple and only contain

```
procedure TForm2.Button1Click(Sender: TObject);
begin
  Chromium1:=TChromium.Create(self);
  Chromium1.Parent:=self;
  Chromium1.Align:=alclient;
  Chromium1.OnLoadError := Chromium1LoadError;
  Chromium1.Load('www.hxyblo.com');
end;

procedure TForm2.Chromium1LoadError(Sender: TObject; const browser:
    ICefBrowser; const frame: ICefFrame; errorCode: Integer; const errorText,
    failedUrl: ustring);
begin
  ShowMessage(errorCode.ToString + #13#10 + failedUrl);
end;
```

But the 64-bit exe works as expected using XE6. The page fail to load and the message is shown.

(I am using the latest source from branch 2454)

**Comment by felipedaragon** [comment]
RJ35 - Your example works as expected. I get the crash when I try creating it within TCustomControl. I noticed now that I have to set not only the OnLoadError (as you can see below) but the OnLoadEnd event too or it doesn't happens

```
unit CrmContainer;

interface

uses
  System.Classes, Vcl.Controls, Vcl.Graphics, cefvcl, ceflib;

type
  TContainer = class(TCustomControl)
  private
    fCrm: TChromium;
    procedure crmLoadEnd(Sender: TObject; const Browser: ICefBrowser;
      const frame: ICefFrame; httpStatusCode: integer);
    procedure crmLoadError(Sender: TObject; const Browser: ICefBrowser;
      const frame: ICefFrame; errorCode: integer;
      const errorText, failedUrl: ustring);
  public
    constructor Create(AOwner: TComponent); override;
    destructor Destroy; override;
    property Crm:TChromium read fCrm;
  end;

implementation

procedure TContainer.crmLoadEnd(Sender: TObject; const Browser: ICefBrowser;
  const frame: ICefFrame; httpStatusCode: integer);
begin
  // nothing
end;

procedure TContainer.crmLoadError(Sender: TObject; const Browser: ICefBrowser;
  const frame: ICefFrame; errorCode: integer;
  const errorText, failedUrl: ustring);
begin
  // nothing
end;

constructor TContainer.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  ControlStyle := ControlStyle + [csAcceptsControls];
  fCrm := TChromium.Create(nil);
  fCrm.Parent := self;
  fCrm.Align := alclient;
  fCrm.OnLoadEnd := crmLoadEnd;
  fCrm.OnLoadError := crmLoadError;
end;

destructor TContainer.Destroy;
begin
  fCrm.Free;
  inherited Destroy;
end;

end.
```

Create example:

```
procedure TForm1.Button1Click(Sender: TObject);
var  CatCrm: TContainer;
begin
     CatCrm:= TContainer.Create(self);
     CatCrm.Parent:=self;
     CatCrm.Align:=AlClient;
     CatCrm.crm.Load('www.cnn.com');
end;
```

This will produce an AV when in 64-bit, but work fine in 32-bit. Using branch DCEF3 2454 and cef_binary_3.2454.1344.g2782fb8_windows64.

If I switch to WACEF branch 2357, this same code will work both in 64-bit and 32-bit (using the binaries from 2357 of course)

**Comment by felipedaragon** [comment]
For the dpr I used:

```
program testcrash;

uses
  Vcl.Forms,
  ceflib, cefvcl, sysutils,
  Unit1 in 'Unit1.pas' {Form1};

{$R *.res}

var
  ProgDir : string;

begin
  ProgDir := extractfilepath(paramstr(0));
  CefLocalesDirPath := ProgDir + 'Packs\CEF\Locales\';
  CefResourcesDirPath := ProgDir + 'Packs\CEF\Resources\';
  CefSingleProcess := False;
  if not CefLoadLibDefault then Exit;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
```

I've the corresponding locales and resource paks under these dirs

**Comment by RJ35** [comment]
OK, now I get the AV.

I suspect it's a window handle issue when creating the Chromium component inside the TCustomControl.

I think the problem can be found in

```
cefvcl.pas

procedure TCustomChromium.CreateBrowser;
```

somewhere. But the error message is less than helpful :(

**Comment by RJ35** [comment]
I found the issue. It's the use of the class variable FSettings that causes the problem in "CreateBrowser".

Changing the method to this seems to solve the issue:

```
cefvcl.pas

procedure TCustomChromium.CreateBrowser;
var
  info: TCefWindowInfo;
  rect: TRect;
  setting: TCefBrowserSettings;
begin
  if not (csDesigning in ComponentState) then
  begin
    FillChar(info, SizeOf(info), 0);
    rect := GetClientRect;
    info.Style := WS_CHILD or WS_VISIBLE or WS_CLIPCHILDREN or WS_CLIPSIBLINGS or WS_TABSTOP;
    info.parent_window := Handle;
    info.x := rect.left;
    info.y := rect.top;
    info.Width := rect.right - rect.left;
    info.Height := rect.bottom - rect.top;
    FillChar(setting, SizeOf(TCefBrowserSettings), 0);
    setting.size := SizeOf(TCefBrowserSettings);
    GetSettings(setting);
{$IFDEF CEF_MULTI_THREADED_MESSAGE_LOOP}
    CefBrowserHostCreate(@info, FHandler, FDefaultUrl, @setting, nil);
{$ELSE}
    FBrowser := CefBrowserHostCreateSync(@info, FHandler, '', @setting, nil);
    FBrowserId := FBrowser.Identifier;
{$ENDIF}
  end;
end;
```

This should be changed as well

```
cefvcl.pas

procedure TChromiumDevTools.ShowDevTools(const browser: ICefBrowser;
  inspectElementAt: PCefPoint);
var
  info: TCefWindowInfo;
  rect: TRect;
  setting: TCefBrowserSettings;
begin
  if browser = nil then Exit;

  FillChar(info, SizeOf(info), 0);

  info.parent_window := Handle;
  info.style := WS_CHILD or WS_VISIBLE or WS_CLIPCHILDREN or WS_CLIPSIBLINGS or WS_TABSTOP;
  Rect := GetClientRect;
  info.x := rect.left;
  info.y := rect.top;
  info.Width := rect.right - rect.left;
  info.Height := rect.bottom - rect.top;
  info.window_name := CefString('DevTools');

  FillChar(Setting, SizeOf(Setting), 0);
  Setting.size := SizeOf(Setting);

  Browser.Host.ShowDevTools(@info, TCefClientOwn.Create as ICefClient, @Setting, inspectElementAt);
end;
```

The use of "FSettings" may cause issues elsewhere as well. Henri, could you please look into it?

**Comment by hgourvest** [comment]
I remember I already investigated this issue, there is an AV on unallocated memory. I avoided this issue enlarging memory allocated to FSettings. But depending the new size, sometime it work sometime not. You should'nt use 64 bit version, really.

**Comment by felipedaragon** [comment]
Hi RJ35 - Yup, your patch gets rid of the AV. Thank you!

Henri - "You should'nt use 64 bit version, really." but it is working after the patch! :)

**Comment by felipedaragon** [comment]
Also, reading cefbuilds.com I see Mac 64bit marked as experimental, but not Windows 64bit

**Comment by hgourvest** [comment]
the last time I checked it was

Le 21 novembre 2015 19:28:46 GMT+01:00, Felipe Daragon notifications@github.com a écrit :

> Also, reading cefbuilds.com I see Mac 64bit market as experimental, but
> not Windows 64bit
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hgourvest/dcef3/issues/12#issuecomment-158670688

## 

Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by felipedaragon** [comment]
They unmarked just recently https://web.archive.org/web/20150801195224/https://cefbuilds.com/

**Comment by RJ35** [comment]
For very basic HTML file previewing purposes it seems to be reliable enough. I usually test for memory issues using EurekaLog and I can't see any issues after the changes I made. Tested both 32-bit and 64-bit versions.

Henri, do you have a simple code example to recreate the memory issue? If the problem is with the libcef.dll - when exactly does this memory AV occur?
(I just want to know if it may be reliable enough to use for very basic needs).

**Comment by hgourvest** [comment]
Ironically you have reverted to the original code, I moved the setting variable to keep the variable out of the stack because I was suspecting CEF to keep a reference to this variable after the browser was created, the same AV was occurring on previous branch with the setting variable in the stack. If it now working again, I see no reason the keep it out of the stack and I will make the change very soon in this branch.

**Comment by hgourvest** [comment]
ok, it is commited, thanks RJ35 and Felipe
