### ISSUE TITLE
Enter-Key in JavaScript KeyUp not working

### ISSUE THREAD

**Issue by strikeflare** [hgourvest/dcef3#22]
It looks like in branch 2454, the key up event will not be fired on Enter-key from the browser.

If I do something like this in a HTML page

`myTextField.onkeyup = function (e) {
       console.log("keyup: " + e.keyCode);
}`

and click any key, it will work for all keys except for the Enter key. The browser only fires keypress and keydown events for this key. 

I compared it with a CEF3 test app. There it has worked just fine.
You can download it from here: [CEF Builds](https://cefbuilds.com/) on "Branch 2454" > "Test App". 

For testing this event, I uploaded a Test HTML page with a JQuery file:
[TestPage.zip](https://github.com/hgourvest/dcef3/files/246428/TestPage.zip)

Is this a bug or did I miss something?

**Comment by yan871366176** [comment]
Hello, chrome current version is already 50, can be upgraded at any time DCEF3 version?
