### ISSUE TITLE
GetSource freezes

### ISSUE THREAD

**Issue by umpani** [hgourvest/dcef3#33]
Hi,

when i'm using Mainframe.getsource to receive the source, the program sometimes freezes.

https://google.com - is working fine
https://facebook.com (Mainpage without login) - is working fine
https://facebook.com (Mainpage with login) - the program is freezing.

Thanks

**Comment by hgourvest** [comment]
please visit forum and ask questions before reporting here

**Comment by felipedaragon** [comment]
@umpani Not freezing here (using libcef 3.2623), but the callback is never completing (like if the page was loading forever), so it never gets the source for the after login page. This is looking like a libcef bug
