### ISSUE TITLE
VisitDom is never Calling

### ISSUE THREAD

**Issue by umpani** [hgourvest/dcef3#34]
Hi,

I tried to use mainframe.visitdom to itterate through the DOM. But the callback procedure is never calling. 

  FBrowser.Browser.Mainframe.VisitDomProc(DOMCallback);

I tried although 
  FBrowser.Browser.Mainframe.VisitDom(TCefFastDomVisitor.Create(DOMCallback));

```
procedure DOMCallback(const Document: ICefDomDocument);
```

  begin
    ShowMessage(Document.Body.GetValue);
  end;

**Comment by hgourvest** [comment]
please visit forum and ask questions before reporting here
