### ISSUE TITLE
Adding onFaviconChange support

### ISSUE THREAD

**Issue by abzalov** [hgourvest/dcef3#4]
There are plans to add the ability to track the favicon changes?

In CEF3 recently added this possibility (https://code.google.com/p/chromiumembedded/issues/detail?id=964).

I'd love to use it.
Thanks!

**Comment by hgourvest** [comment]
this fix is included in branch 2378, this branch is unstable.

**Comment by abzalov** [comment]
I was added necessary changes to implement this, but on application starting always was error "AccessViolation" in OnTooltip. Now I understand why - libraries in DCEF3 are from the stable brunch of CEF3.

I will wait when this change in CEF3 will be in stable brunch.
Thanks!
