### ISSUE TITLE
Huge memory consumption when Options.ImageLoading set to STATE_DISABLED

### ISSUE THREAD

**Issue by thefunkyjoint** [hgourvest/dcef3#44]
I'm using branch 2704.

With default options. TChromium won't consume much memory over time, never reaching more than 200-250mb.

But if i set Options.ImageLoading to STATE_DISABLED, after some time loading pages i can see the memory increasing and easily going on > 1GB, just by loading pages. This problem is easily reproduced by using a TTimer to loop page loading each 10 seconds, for instance.

**Comment by hgourvest** [comment]
this branch is very unstable, the problem come from CEF binaries
DCEF is a Delphi binding for CEF
