### ISSUE TITLE
Are there updates of Chrome DLLs for DCEF3 to keep updated with new internet standards

### ISSUE THREAD

**Issue by renaud69** [hgourvest/dcef3#49]
Hi, I have some strange behaviour of Chromium DCEF-2454 with Delphi 7. It seems to be freezing. I can download a page and then suddenly is freezing... If I try to use the LoadUrl again command then LoadStart event is no more triggered.

Any idea where it can come from ?
Is that due to some Java Script that is not supported by my DCEF version ?
Are there DLLs or code updates required to have more stable version ?

Hope someone can help me.

Regards. Renaud.

**Comment by felipedaragon** [comment]
Hi @renaud69,  I believe DCEF is now only being tested with newer Delphi versions. Maybe @hgourvest can give you a better answer and advice

**Comment by renaud69** [comment]
Thank you Felipe for your answer.. 

Yes maybe I will move to more recent version of Delphi... but want to make sure that DCEF is really stable and that I will not have problems like the one I have... if I move to a new version of Delphi.

I am looking for stable programming environment and want to make sure that DCEF has some future as an embedded browser...

**Comment by renaud69** [comment]
What is the Delphi version that you recommend to use with DCEF3 ?

**Comment by thefunkyjoint** [comment]
I use with Delphi 2007 and it works very well. Just need an update to a newer CEF version.

**Comment by felipedaragon** [comment]
I consider D2007 too old :) Better go with XE2 or newer

**Comment by thefunkyjoint** [comment]
I don't see any advantages to upgrade in my case ; D2007 does all i need for my current Win32 apps. For web apps i switched to standard JS / CSS / HTML.

**Comment by ghost** [comment]
I think that, DSEF is independent of the version IDE
