### ISSUE TITLE
Any Guild to Modify CefLib & CefApi (Current Build is 2840)

### ISSUE THREAD

**Issue by LookGreen** [hgourvest/dcef3#58]
Windows 32-bit Builds, now is 2840.
http://opensource.spotify.com/cefbuilds/index.html
How we can modify core of dcef3 or Any Guild to make it?
I think many developers want to help but don't know how to start to code it (which part what should start).
I tried to see "Comparing changes" on Dcef3 of build 2623 & 2704 
but I don't understand what is main concept of each build.

**Comment by edwinyzh** [comment]
+1

**Comment by thefunkyjoint** [comment]
+1, i love this component but the CEF core is becoming too old.

**Comment by hgourvest** [comment]
I translate c API for about 20 years, and this one is the most complicated I had to translate, there is no simple instructions to achieve this job. It is hard, and you need experience.
It is open source, just fork the project and make a try.

I am too busy now to work on this project, I will be available on January.

**Comment by LookGreen** [comment]
thanks you for your kindness.
we will try to study it.
clue is on C header & src.

**Comment by thefunkyjoint** [comment]
@hgourvest Thanks for answering. Please don't abandon this project, it's really useful ! January is fine, as long as the project keeps alive. I don't have any C experience myself, have no idea how to do it. But i'd be  glad to contribute with some bucks ;)

**Comment by manopera** [comment]
Thank You Henri Gourvest for good work. May you please add support how to access DOM objects , like window object or any global variable, and how to increase size for Web SQL, I use sqlite3 from chromium using javascript and I'm not able to save more than 400 Mb, even if I request 2Gb when creating the database with "openDatabase" ... please help

**Comment by astral2k5** [comment]
@hgourvest Thanks for your work on this. Do you have any update when there will be an update?
Thanks again!

**Comment by hgourvest** [comment]
I am working on.
